#!/bin/bash

echo "🌐 Guide pour contourner l'erreur SSL dans Chrome"
echo "==============================================="

echo ""
echo "🔓 MÉTHODE 1: Accepter le certificat dans Chrome"
echo "------------------------------------------------"
echo "1. Allez sur https://10.100.9.40"
echo "2. Vous verrez l'erreur 'Votre connexion n'est pas privée'"
echo "3. Cliquez sur 'Avancé' (en bas de la page)"
echo "4. Cliquez sur 'Continuer vers 10.100.9.40 (non sécurisé)'"
echo "5. Chrome va accepter le certificat pour cette session"

echo ""
echo "🦊 MÉTHODE 2: Utiliser Firefox (Plus permissif)"
echo "-----------------------------------------------"
echo "1. Ouvrez Firefox"
echo "2. Allez sur https://10.100.9.40"
echo "3. Cliquez sur 'Avancé'"
echo "4. Cliquez sur 'Accepter le risque et continuer'"
echo "5. Firefox va accepter le certificat définitivement"

echo ""
echo "🔧 MÉTHODE 3: Chrome avec options spéciales"
echo "------------------------------------------"
echo "Lancez Chrome avec ces options :"
echo ""
echo "Sur Linux :"
echo "google-chrome --ignore-certificate-errors --ignore-ssl-errors --allow-running-insecure-content https://10.100.9.40"
echo ""
echo "Sur Windows :"
echo "chrome.exe --ignore-certificate-errors --ignore-ssl-errors --allow-running-insecure-content https://10.100.9.40"
echo ""
echo "Sur Mac :"
echo "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors --ignore-ssl-errors --allow-running-insecure-content https://10.100.9.40"

echo ""
echo "🔒 MÉTHODE 4: Ajouter le certificat au système"
echo "---------------------------------------------"
echo "1. Téléchargez le certificat :"
echo "   openssl s_client -connect 10.100.9.40:443 -servername 10.100.9.40 < /dev/null | openssl x509 -outform PEM > myjourney.crt"
echo ""
echo "2. Sur Linux (Ubuntu/Debian) :"
echo "   sudo cp myjourney.crt /usr/local/share/ca-certificates/"
echo "   sudo update-ca-certificates"
echo ""
echo "3. Sur Windows :"
echo "   - Double-cliquez sur myjourney.crt"
echo "   - Cliquez sur 'Installer le certificat'"
echo "   - Choisissez 'Ordinateur local'"
echo "   - Placez dans 'Autorités de certification racines de confiance'"

echo ""
echo "🧪 MÉTHODE 5: Test sans HTTPS"
echo "-----------------------------"
echo "Testez d'abord en HTTP pour vérifier que l'application fonctionne :"
echo "http://10.100.9.40/test"
echo ""
echo "Si ça fonctionne, le problème est uniquement le certificat SSL"

echo ""
echo "✅ RECOMMANDATION"
echo "=================="
echo "Pour un environnement de test/développement :"
echo "👉 Utilisez la MÉTHODE 1 (Accepter dans Chrome)"
echo ""
echo "Pour un environnement de production :"
echo "👉 Configurez un vrai certificat SSL avec Let's Encrypt"
echo "   ./setup-letsencrypt.sh"

echo ""
echo "🔍 DIAGNOSTIC"
echo "============="
echo "Testez ces URLs pour identifier le problème :"
echo "1. http://10.100.9.40/test  (devrait fonctionner)"
echo "2. https://10.100.9.40/test (erreur SSL)"
echo "3. https://10.100.9.40      (erreur SSL)"