#!/bin/bash

echo "🌐 GUIDE COMPLET - Contourner l'erreur SSL dans Chrome/Edge"
echo "=========================================================="

echo ""
echo "🔓 MÉTHODE 1: Mot magique Chrome (La plus simple)"
echo "================================================"
echo "1. Allez sur https://10.100.9.40"
echo "2. Vous verrez l'erreur SSL"
echo "3. Cliquez n'importe où sur la page"
echo "4. Tapez exactement : thisisunsafe"
echo "5. Chrome va accepter le certificat automatiquement"
echo ""
echo "⚠️  Important : Tapez 'thisisunsafe' sans espace, directement sur la page d'erreur"

echo ""
echo "🔧 MÉTHODE 2: Edge - Accepter le certificat"
echo "==========================================="
echo "1. Allez sur https://10.100.9.40"
echo "2. Cliquez sur 'Avancé'"
echo "3. Cliquez sur 'Continuer vers 10.100.9.40 (non sécurisé)'"
echo "4. Edge va accepter le certificat"

echo ""
echo "🦊 MÉTHODE 3: Firefox (Plus permissif)"
echo "======================================"
echo "1. Ouvrez Firefox"
echo "2. Allez sur https://10.100.9.40"
echo "3. Cliquez sur 'Avancé'"
echo "4. Cliquez sur 'Accepter le risque et continuer'"
echo "5. Firefox accepte plus facilement les certificats auto-signés"

echo ""
echo "🚀 MÉTHODE 4: Chrome avec flags (Développeurs)"
echo "=============================================="
echo "Lancez Chrome avec ces options :"
echo ""
echo "Linux :"
echo "google-chrome --ignore-certificate-errors --ignore-ssl-errors --disable-web-security --user-data-dir=/tmp/chrome_dev"
echo ""
echo "Windows :"
echo "chrome.exe --ignore-certificate-errors --ignore-ssl-errors --disable-web-security --user-data-dir=c:\\temp\\chrome_dev"
echo ""
echo "Mac :"
echo "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --ignore-certificate-errors --ignore-ssl-errors --disable-web-security --user-data-dir=/tmp/chrome_dev"

echo ""
echo "🔒 MÉTHODE 5: Ajouter le certificat au système"
echo "=============================================="
echo "1. Téléchargez le certificat :"
echo "   echo | openssl s_client -connect 10.100.9.40:443 2>/dev/null | openssl x509 > myjourney.crt"
echo ""
echo "2. Windows :"
echo "   - Double-cliquez sur myjourney.crt"
echo "   - 'Installer le certificat' → 'Ordinateur local'"
echo "   - 'Autorités de certification racines de confiance'"
echo ""
echo "3. Linux :"
echo "   sudo cp myjourney.crt /usr/local/share/ca-certificates/"
echo "   sudo update-ca-certificates"
echo "   Redémarrez Chrome"
echo ""
echo "4. Mac :"
echo "   - Double-cliquez sur myjourney.crt"
echo "   - Ajoutez au trousseau 'Système'"
echo "   - Double-cliquez sur le certificat dans le trousseau"
echo "   - Changez 'SSL' à 'Toujours faire confiance'"

echo ""
echo "🔓 MÉTHODE 6: Utiliser HTTP temporairement"
echo "=========================================="
echo "Si rien ne fonctionne, utilisez HTTP (sans SSL) :"
echo "👉 http://10.100.9.40"
echo "👉 http://10.100.9.40/test"
echo ""
echo "Cela contourne complètement le problème SSL"

echo ""
echo "✅ RECOMMANDATIONS PAR ORDRE DE PRÉFÉRENCE"
echo "=========================================="
echo "1. 🥇 Tapez 'thisisunsafe' dans Chrome (le plus simple)"
echo "2. 🥈 Utilisez Firefox (plus permissif)"
echo "3. 🥉 Utilisez HTTP temporairement"
echo "4. 🔧 Ajoutez le certificat au système (solution permanente)"

echo ""
echo "🧪 TESTS POUR IDENTIFIER LE PROBLÈME"
echo "===================================="
echo "Testez ces URLs dans l'ordre :"
echo "1. http://10.100.9.40/test  → Devrait afficher 'HTTP Test OK'"
echo "2. https://10.100.9.40/test → Erreur SSL"
echo "3. Après contournement → Devrait fonctionner"

echo ""
echo "💡 Si aucune méthode ne fonctionne, le problème peut être :"
echo "   - Proxy d'entreprise bloquant les certificats auto-signés"
echo "   - Politique de sécurité stricte"
echo "   - Antivirus bloquant les connexions"